### PR TITLE
fix(CollectiveStorage): adjust `getOwner` to NC31

### PR DESCRIPTION
**Pull request by mejo-**
### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits

### CODE REVIEW

**Comment by max-nextcloud** [comment]
Wait... that change looks like it's only adding a return type to the function.

Would this break with NC <= 30 because PHP does not yet support that syntax

**Review by max-nextcloud — COMMENTED** [review]
Not sure if this actually has the full change.

**Comment by mejo-** [comment]
> Wait... that change looks like it's only adding a return type to the function.
> 
> Would this break with NC <= 30 because PHP does not yet support that syntax

Exactly, it only adds the return type to be in line with the parent class on Nextcloud 31. I first thought it would then be incompatible with the parent classes on Nextcloud 30 and below, but manual testing and CI both proved me wrong. So should be good to be merged :blush:

**Review by provokateurin — APPROVED** [review]
Sorry for this :see_no_evil:

**Review by blizzz — APPROVED** [review]

**Pull request merged**
