### PR TITLE
Fix of inconsistent and confusing public share wording

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
I'm correcting the wording of the share button because : 
- it creates confusion with the notion of “guest” (in relation to the “Guests” app). This app should have exclusive rights to the notion of guest.
- it is inconsistent in terms of vocabulary with what already exists in the Photos app for a rather similar context, which uses “Share via public link”.
- Fixes: #1225

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by Jerome-Herbinet** [comment]
Do I have to worry of Cypress errors ?

**Review by jancborchardt — CHANGES_REQUESTED** [review]
We should never use the wording "public link" since it sounds like publishing something. The link is still not guessable, thus not public.

In Files we use "Share link", which is what we should use here (and in Photos) as well. :)

**Comment by Jerome-Herbinet** [comment]
> We should never use the wording "public link" since it sounds like publishing something. The link is still not guessable, thus not public.
> 
> In Files we use "Share link", which is what we should use here (and in Photos) as well. :)

@jancborchardt, thanks for your reply. "Share link" is relevant with "Files", in the sharing properties on the right-hand side panel. In "Share link" describes what it is, but not the action. Do you think that we can use share link like this ? (see screenshot) : 

I ask this question because, except “settings”, all the available options use an action verb. So “share link” doesn't seem to be well expressed in this part of the interface. So I still suggest using the verb “Share”, but with something else to complete instead of “via public link”. What do you suggest? (keep in mind that only “share” isn't enough, as users might think that sharing can also be done with other users (too general a word).

I also notice (see the screenshot) that en share entry is displayed twice. Strange, isn't it ?

**Comment by mejo-** [comment]
> I still suggest using the verb “Share”, but with something else to complete instead of “via public link”.

Actually "Share link" contains an action verb, which is "share", no? You can read it as a short form of "Share the link" or "Share via link".

> I also notice (see the screenshot) that en share entry is displayed twice. Strange, isn't it ?

Oh, that's another bug. If you don't mind I push a fix for this into your PR.

**Review by mejo- — APPROVED** [review]

**Pull request merged**
