### PR TITLE
Add modal to move pages inside the collective

### PR DESCRIPTION
**Pull request by mejo-**
### 📝 Summary

Allows to move pages between subpages and in sort order inside

Fixes: #462

#### 🖼️ Screenshots

Action | Modal
---|---
2023-01-01T22:35:26,492573140+01:00 | 2023-01-01T22:35:12,193365414+01:00 |

#### Screencast

[recording.webm](https://user-images.githubusercontent.com/3582805/210185543-c6491c9b-2f42-4976-9eca-842829edab7f.webm)

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] Tests (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [x] Documentation ([README](https://github.com/nextcloud/collectives/blob/main/README.md) or [documentation](https://github.com/nextcloud/collectives/blob/main/docs/)) has been updated or is not required

### CODE REVIEW

**Comment by mejo-** [comment]
@jancborchardt and @nimishavijay also curious about your feedback :blush:

**Review by max-nextcloud — APPROVED** [review]
:partying_face: Woohooo!

Super slick, focussed, and easy to understand interface.

Code looks good as well and tests included... so i don't have to test it ;)

**Review by nimishavijay — DISMISSED** [review]
Super nice work! :D Looks very nice! Few things I noticed:
- "Choose target" --> "Move page" as it is less technical
- It would be nice to have some space around the breadcrumbs bar, as it looks quite tight now. We could make it such that the height is 44px, similar to the appearance of the [breadcrumbs vue component](https://github.com/nextcloud/nextcloud-vue/pull/2411)
- Along the same lines, we could also use a button-style hover feedback on the breadcrumbs for better accessibility 
- There could also be more margin on the left of the emoji in the page list -- so that it looks similar to the page list in the left part of the content 

Other then those spacing changes I think it looks great! Any more feedback @jancborchardt ? :)

**Comment by juliushaertl** [comment]
Very nice 👍

**Review by juliushaertl — APPROVED** [review]

**Comment by mejo-** [comment]
Thanks for the feedback @nimishavijay! I worked a bit more on the breadcrumbs, see the result below. Also, I did a few improvements for better keyboard navigation via tab:

[recording2.webm](https://user-images.githubusercontent.com/3582805/210642653-7003cdaf-0b99-4eb4-9cc3-209934991bec.webm)

[recording3.webm](https://user-images.githubusercontent.com/3582805/210642674-d24c1124-f7d1-4ebd-b54e-951b1ae67cfb.webm)

**Comment by mejo-** [comment]
Ah, and I changed the title of the modal to "Move page" only after recording the screencasts :see_no_evil:

**Pull request merged**
