### PR TITLE
fix: Fallback to old eventdispatcher on older releases

### PR DESCRIPTION
**Pull request by juliushaertl**
Fix https://github.com/nextcloud/collectives/issues/828

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] Tests (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [ ] Documentation ([README](https://github.com/nextcloud/collectives/blob/main/README.md) or [documentation](https://github.com/nextcloud/collectives/blob/main/docs/)) has been updated or is not required

### CODE REVIEW

**Comment by juliushaertl** [comment]
Let me just push a unit test to assert the relevant bits, a full test for the background job is more tricky

**Comment by juliushaertl** [comment]
Pushed, though the test is not very fancy

**Review by max-nextcloud — APPROVED** [review]
Thanks for the test! :tada:

**Review by theroch — APPROVED** [review]
I've have running this patch for several days now without any issues.

**Comment by level420** [comment]
manually applied the PR and it works as exptected.
please release a new version of circes compatible with nextcloud 27 (and 26) with this PR!

**Pull request merged**
