### PR TITLE
Address Nextcloud 30 design review comments

### PR DESCRIPTION
**Pull request by mejo-**
### 📝 Summary

* Resolves: #1397 

#### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
grafik | grafik
---|---
grafik | grafik
---|---
grafik | grafik
---|---
grafik | grafik
--- | ---
grafik | grafik
---|---
grafik | grafik
---|---
grafik | grafik
---|---
grafik | grafik
---|---
grafik | grafik
--- | ---
grafik | grafik

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] Tests (unit, integration and/or end-to-end) passing and the changes are covered with tests

### CODE REVIEW

**Review by jancborchardt — CHANGES_REQUESTED** [review]
Nice! Some feedback:
- [ ] Modal first step:
  - [ ] The emptycontent icon seems placed too low, not vertically centered
  - [ ] "Cancel" button was fine on the left and without icon. Placing it next to the "Add members" button can lead to misclicks, and giving it an icon gives it too much importance.
- [ ] Add members step:
  - [ ] The emptycontent text seems a bit superfluous, duplicate from the search label?
  - [ ] Same here with the "Back" button as with the "Cancel" button before
- [ ] Pages: We noted during the design review that page titles would look better in bold as proper h2 heading styles.
- [ ] Attachments sidebar: This seems to have a misunderstanding :) What I meant was to adjust it so the bold text stays "No attachments available" (otherwise this is too much text for a heading). The current text "If the page has attachments, they will be listed here" is replaced with the text of the infobox as it is more informative, and the infobox style is removed as it is an unnecessary different style.

Thank you! :)

**Comment by mejo-** [comment]
>  "Cancel" button was fine on the left and without icon. Placing it next to the "Add members" button can lead to misclicks, and giving it an icon gives it too much importance.

This is how buttons are aligned in `NcDialog`. I could hack this with a `:deep()` selector, but should I also do this for the second step of the new collectives modal than as well?

**Comment by mejo-** [comment]
> Add members step:
> - The emptycontent text seems a bit superfluous, duplicate from the search label?

What do you mean here? In the second step of the new collective modal, there's no empty content displayed anymore, because it loads a list of potential members to add straight away :thinking:

**Comment by mejo-** [comment]
Thanks @jancborchardt, addressed all your follow-up comments with one further question and updated the screenshots. Would you mind to review again?

**Review by jancborchardt — APPROVED** [review]
Awesome @mejo-, looks really great! :)

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
