### PR TITLE
Favorite pages

### PR DESCRIPTION
**Pull request by mejo-**
### 📝 Summary

Allow to mark pages as favorites. Favorites will get additionally listed in a collapsible "Favorites" section at the top of the page list.

Resolves: #300 

#### 🖼️ Screenshots

No Favorites | Favorites expanded | Favorites collapsed | Favorites actions
---|--- | --- | ---
image | image | image | image

| Screencast |
| --- |
| recording1 |

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [x] Tests (unit, integration and/or end-to-end) passing and the changes are covered with tests

### CODE REVIEW

**Review by jancborchardt — APPROVED** [review]
Looks really really nice! :) I have no change requests, and am looking forward to using it in action!

**Review by nimishavijay — APPROVED** [review]
Awesome! That looks super nice! 🚀 
Only one small change: the chevron arrow on the "Favorites" item should be on the right, so that it's center aligned with the `+` button of the other pages :) Other than that it's perfect! 
Approving to not block for another day 😅 Looking forward to seeing this in our handbook!

**Comment by mejo-** [comment]
> Only one small change: the chevron arrow on the "Favorites" item should be on the right, so that it's center aligned with the + button of the other pages :) Other than that it's perfect!

Good point, changed now:

image

**Review by juliusknorr — APPROVED** [review]
Very nice 👍

**Pull request merged**
