### PR TITLE
fix(PageTrashBackend): Ignore emty relativePath in `getTrashNodeById()`

### PR DESCRIPTION
**Pull request by mejo-**
### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits

### CODE REVIEW

**Comment by max-nextcloud** [comment]
I don't understand this based on the commit alone. Why would there be no relative path? What does this fix? Could you add a test or a trace or a link to an issue or so?

**Comment by blizzz** [comment]
By API it may return null, so formally the changed handling is correct, alas I have the same questions as Max (going down the code only a little).

**Comment by max-nextcloud** [comment]
<details>
<summary>I found a trace in the office chat.</summary>

```json
{
  "Exception": "TypeError",
  "Message": "explode(): Argument #2 ($string) must be of type string, null given",
  "Code": 0,
  "Trace": [
    {
      "file": "/var/www/cloud.nextcloud.com/nextcloud/apps/collectives/lib/Trash/PageTrashBackend.php",
      "line": 512,
      "function": "explode",
      "args": [
        "/",
        null
      ]
    },
    {
      "file": "/var/www/cloud.nextcloud.com/nextcloud/apps/files_trashbin/lib/Trash/TrashManager.php",
      "line": 112,
      "function": "getTrashNodeById",
      "class": "OCA\\Collectives\\Trash\\PageTrashBackend",
      "type": "->",
      "args": [
        [
          "OC\\User\\User"
        ],
        6951158
      ]
    },
    {
      "file": "/var/www/cloud.nextcloud.com/nextcloud/apps/files_trashbin/lib/Controller/PreviewController.php",
      "line": 101,
      "function": "getTrashNodeById",
      "class": "OCA\\Files_Trashbin\\Trash\\TrashManager",
      "type": "->",
      "args": [
        [
          "OC\\User\\User"
        ],
        6951158
      ]
    },
    {
      "file": "/var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
      "line": 230,
      "function": "getPreview",
      "class": "OCA\\Files_Trashbin\\Controller\\PreviewController",
      "type": "->",
      "args": [
        6951158,
        32,
        32,
        true
      ]
    },
    {
      "file": "/var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
      "line": 137,
      "function": "executeController",
      "class": "OC\\AppFramework\\Http\\Dispatcher",
      "type": "->",
      "args": [
        [
          "OCA\\Files_Trashbin\\Controller\\PreviewController"
        ],
        "getPreview"
      ]
    },
    {
      "file": "/var/www/cloud.nextcloud.com/nextcloud/lib/private/AppFramework/App.php",
      "line": 183,
      "function": "dispatch",
      "class": "OC\\AppFramework\\Http\\Dispatcher",
      "type": "->",
      "args": [
        [
          "OCA\\Files_Trashbin\\Controller\\PreviewController"
        ],
        "getPreview"
      ]
    },
    {
      "file": "/var/www/cloud.nextcloud.com/nextcloud/lib/private/Route/Router.php",
      "line": 315,
      "function": "main",
      "class": "OC\\AppFramework\\App",
      "type": "::",
      "args": [
        "OCA\\Files_Trashbin\\Controller\\PreviewController",
        "getPreview",
        [
          "OC\\AppFramework\\DependencyInjection\\DIContainer"
        ],
        [
          "files_trashbin.Preview.getPreview"
        ]
      ]
    },
    {
      "file": "/var/www/cloud.nextcloud.com/nextcloud/lib/base.php",
      "line": 1068,
      "function": "match",
      "class": "OC\\Route\\Router",
      "type": "->",
      "args": [
        "/apps/files_trashbin/preview"
      ]
    },
    {
      "file": "/var/www/cloud.nextcloud.com/nextcloud/index.php",
      "line": 36,
      "function": "handleRequest",
      "class": "OC",
      "type": "::",
      "args": []
    }
  ],
  "File": "/var/www/cloud.nextcloud.com/nextcloud/apps/collectives/lib/Trash/PageTrashBackend.php",
  "Line": 512
}
```
</details>

**Comment by max-nextcloud** [comment]
The doc comment for `getRelativePath` says:
> Make a path relative to a root path, or return null if the path is outside the root

The code in calling `getTrashNodeById()` also looks like it will happily accept `null` as a return value:

```php

    public function getTrashNodeById(IUser $user, int $fileId) {
        foreach ($this->backends as $backend) {
            $item = $backend->getTrashNodeById($user, $fileId);
            if ($item !== null) {
                return $item;
            }
        }
        return null;
    }

```

**Review by max-nextcloud — APPROVED** [review]

**Comment by mejo-** [comment]
Yeah, sorry for not providing further context in this PR. I had pinged you both on the PR in the relevant conversation in our team chat.

**Pull request merged**
