### PR TITLE
fix(dashboard): Display parent page path in recent pages widget

### PR DESCRIPTION
**Pull request by mejo-**
Fixes: #1010

#### 🖼️ Screenshots

:derelict_house:  Before | 🏡 After
|---|---
2023-11-14T11:36:03,256783199+01:00 | 2023-11-14T11:35:32,870722255+01:00

### CODE REVIEW

**Review by provokateurin — APPROVED** [review]
Maybe a `/` without any space would be better? Then less of the parent page names are cut off

**Comment by mejo-** [comment]
> Maybe a / without any space would be better? Then less of the parent page names are cut off if the subtitle is too long

I tried this before, but I think it's important to separate the collective name from the path to make it easy to grasp which collective this is all about.

**Comment by blizzz** [comment]
The slash is part of the path. Maybe instead of truncating in at the end, the ellipsis should be in the middle, or even beginning? But that would be work on the dashboard side of things.

We could save a bit of space using a colon and sparing the first whitespace, so `: ` instead of ` > ` though.

**Comment by provokateurin** [comment]
Ah sorry I thought the pages were also separate by the `>`. Then this already does what I suggested :)

**Comment by mejo-** [comment]
> The slash is part of the path. Maybe instead of truncating in at the end, the ellipsis should be in the middle, or even beginning? But that would be work on the dashboard side of things.

Yeah, I'd say it's out of scope here.

> We could save a bit of space using a colon and sparing the first whitespace, so : instead of > though.

Well, one character less. But yes, let's do that :blush:

**Comment by mejo-** [comment]
Screenshots updated

**Comment by blizzz** [comment]
> > We could save a bit of space using a colon and sparing the first whitespace, so : instead of > though.
> 
> Well, one character less. But yes, let's do that 😊

It's not monospace, so a few pixels more :superhero:

**Review by blizzz — APPROVED** [review]

**Comment by juliushaertl** [comment]
In the page title we actually use "Page - Parent page - collective", maybe that would be an option to be consistent with separators?

**Comment by blizzz** [comment]
> In the page title we actually use "Page - Parent page - collective", maybe that would be an option to be consistent with separators?

There we don't have an issue with screen estate though, and typically you know on which collective you are, when you open that page. On a concise overview, you do not have this context, making it more important to provide the collective info, I'd say.

**Pull request merged**
