### PR TITLE
[main] Update nextcloud/ocp dependency

### PR DESCRIPTION
**Pull request by nextcloud-command**
Auto-generated update of [nextcloud/ocp](https://github.com/nextcloud-deps/ocp/) dependency

### CODE REVIEW

**Comment by juliushaertl** [comment]
Needs some check:

```
Error: lib/ACL/ACLStorageWrapper.php:62:25: ParamNameMismatch: Argument 1 of OCA\Collectives\ACL\ACLStorageWrapper::rename has wrong name $path1, expecting $source as defined by OCP\Files\Storage\IStorage::rename (see https://psalm.dev/230)
Error: lib/ACL/ACLStorageWrapper.php:62:33: ParamNameMismatch: Argument 2 of OCA\Collectives\ACL\ACLStorageWrapper::rename has wrong name $path2, expecting $target as defined by OCP\Files\Storage\IStorage::rename (see https://psalm.dev/230)
Error: lib/ACL/ACLStorageWrapper.php:84:23: ParamNameMismatch: Argument 1 of OCA\Collectives\ACL\ACLStorageWrapper::copy has wrong name $path1, expecting $source as defined by OCP\Files\Storage\IStorage::copy (see https://psalm.dev/230)
Error: lib/ACL/ACLStorageWrapper.php:84:31: ParamNameMismatch: Argument 2 of OCA\Collectives\ACL\ACLStorageWrapper::copy has wrong name $path2, expecting $target as defined by OCP\Files\Storage\IStorage::copy (see https://psalm.dev/230)
Error: lib/Model/CollectiveInfo.php:28:2: ConstructorSignatureMismatch: Method OCA\Collectives\Model\CollectiveInfo::__construct has more required parameters than parent method OCP\AppFramework\Db\Entity::__construct (see https://psalm.dev/231)
Error: lib/Model/CollectiveShareInfo.php:14:2: ConstructorSignatureMismatch: Method OCA\Collectives\Model\CollectiveShareInfo::__construct has more required parameters than parent method OCP\AppFramework\Db\Entity::__construct (see https://psalm.dev/231)
Error: lib/Reference/SearchablePageReferenceProvider.php:32:3: UndefinedClass: Class, interface or enum named OC\Collaboration\Reference\ReferenceManager does not exist (see https://psalm.dev/019)
Error: lib/Reference/SearchablePageReferenceProvider.php:33:3: UndefinedClass: Class, interface or enum named OC\Collaboration\Reference\LinkReferenceProvider does not exist (see https://psalm.dev/019)
Error: lib/Reference/SearchablePageReferenceProvider.php:81:12: UndefinedClass: Class, interface or enum named OC\Collaboration\Reference\LinkReferenceProvider does not exist (see https://psalm.dev/019)
Error: lib/Reference/SearchablePageReferenceProvider.php:91:12: UndefinedClass: Class, interface or enum named OC\Collaboration\Reference\LinkReferenceProvider does not exist (see https://psalm.dev/019)
Error: lib/Reference/SearchablePageReferenceProvider.php:161:3: UndefinedClass: Class, interface or enum named OC\Collaboration\Reference\ReferenceManager does not exist (see https://psalm.dev/019)
```

**Comment by mejo-** [comment]
This is interesting:

> ERROR: ConstructorSignatureMismatch - lib/Model/CollectiveInfo.php:28:2 - Method OCA\Collectives\Model\CollectiveInfo::__construct has more required parameters than parent method OCP\AppFramework\Db\Entity::__construct (see https://psalm.dev/231)
> 	public function __construct(Collective $collective,

`CollectiveInfo` extends `Collective`. The parent (`Collective`) doesn't have a constructor at all, the child (`CollectiveInfo`) has one with two required parameters. This doesn't cause runtime errors, and so far psalm didn't mourn about it either.

I don't know why exactly psalm complains now, but [psalm docs on `ConstructorSignatureMissmatch`](https://psalm.dev/docs/running_psalm/issues/ConstructorSignatureMismatch/) don't speak about additional required parameters - only about fewer parameters being a problem.

Also, [PHP docs on constructors](https://www.php.net/manual/en/language.oop5.decon.php) mention explicitly that constructor inheritance doesn't require signature compatibility:

> Unlike other methods, [__construct()](https://www.php.net/manual/en/language.oop5.decon.php#object.construct) is exempt from the usual [signature compatibility rules](https://www.php.net/manual/en/language.oop5.basic.php#language.oop.lsp) when being extended.

I see two options of refactoring the code to please psalm:
1. Remove the constructor completely from `CollectiveInfo` and add some `CollectiveInfo->fromCollective()` function to feed the object afterwards. We would always have to do `$collectiveInfo = new CollectiveInfo; $collectiveInfo->fromCollective(...)) in this case.
2. Make all parameters to the constructor optional. This feels unclean though, since a `CollectiveInfo` object without id, name, etc. doesn't make much sense.

I wonder whether pleasing psalm is the right thing to do here at all.

**Comment by mejo-** [comment]
Ok, apparently this no longer works because `Collective` extends `Entity`, and the latter has `@psalm-consistent-constructor` set since https://github.com/nextcloud/server/commit/e91457d9cd68182591038636155d415b5dee0ec4.

**Comment by mejo-** [comment]
We should merge the `...Info` classes and their parent classes into one, like documented here: https://github.com/nextcloud/documentation/pull/11682

**Review by blizzz — APPROVED** [review]
looks good, did not test.

**Pull request merged**
