### PR TITLE
fix(migrations): set default value for new not null column

### PR DESCRIPTION
**Pull request by tcitworld**
Otherwise: `Not null violation: 7 ERREUR:  la colonne « settings » contient des valeurs NULL`

### 🏁 Checklist

- [x] Code is properly formatted (`npm run lint` / `npm run stylelint` / `composer run cs:check`)
- [x] [Sign-off message](https://probot.github.io/apps/dco/) is added to all commits
- [ ] Tests (unit, integration and/or end-to-end) passing and the changes are covered with tests
- [ ] Documentation ([README](https://github.com/nextcloud/collectives/blob/main/README.md) or [documentation](https://github.com/nextcloud/collectives/blob/main/docs/)) has been updated or is not required

### CODE REVIEW

**Review by mejo- — APPROVED** [review]
Thanks @tcitworld! Which DB backend do you use? I wonder why I didn't spot this error while developing the feature :thinking:

**Comment by max-nextcloud** [comment]
@tcitworld We're trying to add a test to prevent such issues in the future. However we have not been able to trigger the error message. Could you provide some insight into the situation so we can better build that test?
1) Which version of PostgreSQL were you using?
2) Did the error prevent the upgrade from working?
3) Where is that exception shown?
4) Can you provide the full output of the log entry in question?
5) Do you know how to trigger the error?

Thanks!

**Comment by tcitworld** [comment]
1. PG 13.11
2. Yes, I had to disable the app to continue the upgrade
3. See logs
4. That's all that was outputted by the command. The log file doesn't give much more informations (see below)
5. I'd make sure to have some elements in the `collectives_u_settings` table *before* the migration is executed, otherwise the issue won't be triggered. Do you have some fixtures for your test?

<details>
<pre>
{
  "reqId": "xjd4W7SGEpuHj3CSb30v",
  "level": 1,
  "time": "2023-10-02T15:55:30+02:00",
  "remoteAddr": "",
  "user": "--",
  "app": "updater",
  "method": "",
  "url": "--",
  "message": "\\OC\\Updater::appUpgradeStarted: Updating <collectives> ...",
  "userAgent": "--",
  "version": "27.1.1.0",
  "data": {
    "app": "updater"
  }
}
{
  "reqId": "xjd4W7SGEpuHj3CSb30v",
  "level": 3,
  "time": "2023-10-02T15:55:32+02:00",
  "remoteAddr": "",
  "user": "--",
  "app": "no app in context",
  "method": "",
  "url": "--",
  "message": "Database error when running migration 020800Date20230911000000 for app collectives\nAn exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERREUR:  la colonne « settings » contient des valeurs NULL",
  "userAgent": "--",
  "version": "27.1.1.0",
  "exception": {
    "Exception": "Exception",
    "Message": "Database error when running migration 020800Date20230911000000 for app collectives\nAn exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERREUR:  la colonne « settings » contient des valeurs NULL",
    "Code": 0,
    "Trace": [
      {
        "file": "nextcloud/lib/private/legacy/OC_App.php",
        "line": 844,
        "function": "migrate",
        "class": "OC\\DB\\MigrationService",
        "type": "->"
      },
      {
        "file": "nextcloud/lib/private/Updater.php",
        "line": 359,
        "function": "updateApp",
        "class": "OC_App",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "nextcloud/lib/private/Updater.php",
        "line": 271,
        "function": "doAppUpgrade",
        "class": "OC\\Updater",
        "type": "->"
      },
      {
        "file": "nextcloud/lib/private/Updater.php",
        "line": 139,
        "function": "doUpgrade",
        "class": "OC\\Updater",
        "type": "->"
      },
      {
        "file": "nextcloud/core/Command/Upgrade.php",
        "line": 225,
        "function": "upgrade",
        "class": "OC\\Updater",
        "type": "->"
      },
      {
        "file": "nextcloud/3rdparty/symfony/console/Command/Command.php",
        "line": 298,
        "function": "execute",
        "class": "OC\\Core\\Command\\Upgrade",
        "type": "->"
      },
      {
        "file": "nextcloud/3rdparty/symfony/console/Application.php",
        "line": 1040,
        "function": "run",
        "class": "Symfony\\Component\\Console\\Command\\Command",
        "type": "->"
      },
      {
        "file": "nextcloud/3rdparty/symfony/console/Application.php",
        "line": 301,
        "function": "doRunCommand",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "nextcloud/3rdparty/symfony/console/Application.php",
        "line": 171,
        "function": "doRun",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "nextcloud/lib/private/Console/Application.php",
        "line": 211,
        "function": "run",
        "class": "Symfony\\Component\\Console\\Application",
        "type": "->"
      },
      {
        "file": "nextcloud/console.php",
        "line": 100,
        "function": "run",
        "class": "OC\\Console\\Application",
        "type": "->"
      },
      {
        "file": "nextcloud/occ",
        "line": 11,
        "args": [
          "nextcloud/console.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "nextcloud/lib/private/DB/MigrationService.php",
    "Line": 421,
    "Previous": {
      "Exception": "Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException",
      "Message": "An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERREUR:  la colonne « settings » contient des valeurs NULL",
      "Code": 7,
      "Trace": [
        {
          "file": "nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
          "line": 1814,
          "function": "convert",
          "class": "Doctrine\\DBAL\\Driver\\API\\PostgreSQL\\ExceptionConverter",
          "type": "->"
        },
        {
          "file": "nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
          "line": 1749,
          "function": "handleDriverException",
          "class": "Doctrine\\DBAL\\Connection",
          "type": "->"
        },
        {
          "file": "nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
          "line": 1055,
          "function": "convertExceptionDuringQuery",
          "class": "Doctrine\\DBAL\\Connection",
          "type": "->"
        },
        {
          "file": "nextcloud/lib/private/DB/Connection.php",
          "line": 262,
          "function": "executeQuery",
          "class": "Doctrine\\DBAL\\Connection",
          "type": "->"
        },
        {
          "file": "nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
          "line": 1843,
          "function": "executeQuery",
          "class": "OC\\DB\\Connection",
          "type": "->"
        },
        {
          "file": "nextcloud/lib/private/DB/Migrator.php",
          "line": 162,
          "function": "query",
          "class": "Doctrine\\DBAL\\Connection",
          "type": "->"
        },
        {
          "file": "nextcloud/lib/private/DB/Migrator.php",
          "line": 68,
          "function": "applySchema",
          "class": "OC\\DB\\Migrator",
          "type": "->"
        },
        {
          "file": "nextcloud/lib/private/DB/Connection.php",
          "line": 589,
          "function": "migrate",
          "class": "OC\\DB\\Migrator",
          "type": "->"
        },
        {
          "file": "nextcloud/lib/private/DB/MigrationService.php",
          "line": 532,
          "function": "migrateToSchema",
          "class": "OC\\DB\\Connection",
          "type": "->"
        },
        {
          "file": "nextcloud/lib/private/DB/MigrationService.php",
          "line": 417,
          "function": "executeStep",
          "class": "OC\\DB\\MigrationService",
          "type": "->"
        },
        {
          "file": "nextcloud/lib/private/legacy/OC_App.php",
          "line": 844,
          "function": "migrate",
          "class": "OC\\DB\\MigrationService",
          "type": "->"
        },
        {
          "file": "nextcloud/lib/private/Updater.php",
          "line": 359,
          "function": "updateApp",
          "class": "OC_App",
          "type": "::",
          "args": [
            "*** sensitive parameters replaced ***"
          ]
        },
        {
          "file": "nextcloud/lib/private/Updater.php",
          "line": 271,
          "function": "doAppUpgrade",
          "class": "OC\\Updater",
          "type": "->"
        },
        {
          "file": "nextcloud/lib/private/Updater.php",
          "line": 139,
          "function": "doUpgrade",
          "class": "OC\\Updater",
          "type": "->"
        },
        {
          "file": "nextcloud/core/Command/Upgrade.php",
          "line": 225,
          "function": "upgrade",
          "class": "OC\\Updater",
          "type": "->"
        },
        {
          "file": "nextcloud/3rdparty/symfony/console/Command/Command.php",
          "line": 298,
          "function": "execute",
          "class": "OC\\Core\\Command\\Upgrade",
          "type": "->"
        },
        {
          "file": "nextcloud/3rdparty/symfony/console/Application.php",
          "line": 1040,
          "function": "run",
          "class": "Symfony\\Component\\Console\\Command\\Command",
          "type": "->"
        },
        {
          "file": "nextcloud/3rdparty/symfony/console/Application.php",
          "line": 301,
          "function": "doRunCommand",
          "class": "Symfony\\Component\\Console\\Application",
          "type": "->"
        },
        {
          "file": "nextcloud/3rdparty/symfony/console/Application.php",
          "line": 171,
          "function": "doRun",
          "class": "Symfony\\Component\\Console\\Application",
          "type": "->"
        },
        {
          "file": "nextcloud/lib/private/Console/Application.php",
          "line": 211,
          "function": "run",
          "class": "Symfony\\Component\\Console\\Application",
          "type": "->"
        },
        {
          "file": "nextcloud/console.php",
          "line": 100,
          "function": "run",
          "class": "OC\\Console\\Application",
          "type": "->"
        },
        {
          "file": "nextcloud/occ",
          "line": 11,
          "args": [
            "nextcloud/console.php"
          ],
          "function": "require_once"
        }
      ],
      "File": "nextcloud/3rdparty/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php",
      "Line": 51,
      "Previous": {
        "Exception": "Doctrine\\DBAL\\Driver\\PDO\\Exception",
        "Message": "SQLSTATE[23502]: Not null violation: 7 ERREUR:  la colonne « settings » contient des valeurs NULL",
        "Code": 7,
        "Trace": [
          {
            "file": "nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php",
            "line": 77,
            "function": "new",
            "class": "Doctrine\\DBAL\\Driver\\PDO\\Exception",
            "type": "::"
          },
          {
            "file": "nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
            "line": 1050,
            "function": "query",
            "class": "Doctrine\\DBAL\\Driver\\PDO\\Connection",
            "type": "->"
          },
          {
            "file": "nextcloud/lib/private/DB/Connection.php",
            "line": 262,
            "function": "executeQuery",
            "class": "Doctrine\\DBAL\\Connection",
            "type": "->"
          },
          {
            "file": "nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
            "line": 1843,
            "function": "executeQuery",
            "class": "OC\\DB\\Connection",
            "type": "->"
          },
          {
            "file": "nextcloud/lib/private/DB/Migrator.php",
            "line": 162,
            "function": "query",
            "class": "Doctrine\\DBAL\\Connection",
            "type": "->"
          },
          {
            "file": "nextcloud/lib/private/DB/Migrator.php",
            "line": 68,
            "function": "applySchema",
            "class": "OC\\DB\\Migrator",
            "type": "->"
          },
          {
            "file": "nextcloud/lib/private/DB/Connection.php",
            "line": 589,
            "function": "migrate",
            "class": "OC\\DB\\Migrator",
            "type": "->"
          },
          {
            "file": "nextcloud/lib/private/DB/MigrationService.php",
            "line": 532,
            "function": "migrateToSchema",
            "class": "OC\\DB\\Connection",
            "type": "->"
          },
          {
            "file": "nextcloud/lib/private/DB/MigrationService.php",
            "line": 417,
            "function": "executeStep",
            "class": "OC\\DB\\MigrationService",
            "type": "->"
          },
          {
            "file": "nextcloud/lib/private/legacy/OC_App.php",
            "line": 844,
            "function": "migrate",
            "class": "OC\\DB\\MigrationService",
            "type": "->"
          },
          {
            "file": "nextcloud/lib/private/Updater.php",
            "line": 359,
            "function": "updateApp",
            "class": "OC_App",
            "type": "::",
            "args": [
              "*** sensitive parameters replaced ***"
            ]
          },
          {
            "file": "nextcloud/lib/private/Updater.php",
            "line": 271,
            "function": "doAppUpgrade",
            "class": "OC\\Updater",
            "type": "->"
          },
          {
            "file": "nextcloud/lib/private/Updater.php",
            "line": 139,
            "function": "doUpgrade",
            "class": "OC\\Updater",
            "type": "->"
          },
          {
            "file": "nextcloud/core/Command/Upgrade.php",
            "line": 225,
            "function": "upgrade",
            "class": "OC\\Updater",
            "type": "->"
          },
          {
            "file": "nextcloud/3rdparty/symfony/console/Command/Command.php",
            "line": 298,
            "function": "execute",
            "class": "OC\\Core\\Command\\Upgrade",
            "type": "->"
          },
          {
            "file": "nextcloud/3rdparty/symfony/console/Application.php",
            "line": 1040,
            "function": "run",
            "class": "Symfony\\Component\\Console\\Command\\Command",
            "type": "->"
          },
          {
            "file": "nextcloud/3rdparty/symfony/console/Application.php",
            "line": 301,
            "function": "doRunCommand",
            "class": "Symfony\\Component\\Console\\Application",
            "type": "->"
          },
          {
            "file": "nextcloud/3rdparty/symfony/console/Application.php",
            "line": 171,
            "function": "doRun",
            "class": "Symfony\\Component\\Console\\Application",
            "type": "->"
          },
          {
            "file": "nextcloud/lib/private/Console/Application.php",
            "line": 211,
            "function": "run",
            "class": "Symfony\\Component\\Console\\Application",
            "type": "->"
          },
          {
            "file": "nextcloud/console.php",
            "line": 100,
            "function": "run",
            "class": "OC\\Console\\Application",
            "type": "->"
          },
          {
            "file": "nextcloud/occ",
            "line": 11,
            "args": [
              "nextcloud/console.php"
            ],
            "function": "require_once"
          }
        ],
        "File": "nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php",
        "Line": 30,
        "Previous": {
          "Exception": "PDOException",
          "Message": "SQLSTATE[23502]: Not null violation: 7 ERREUR:  la colonne « settings » contient des valeurs NULL",
          "Code": "23502",
          "Trace": [
            {
              "file": "nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php",
              "line": 72,
              "function": "query",
              "class": "PDO",
              "type": "->"
            },
            {
              "file": "nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
              "line": 1050,
              "function": "query",
              "class": "Doctrine\\DBAL\\Driver\\PDO\\Connection",
              "type": "->"
            },
            {
              "file": "nextcloud/lib/private/DB/Connection.php",
              "line": 262,
              "function": "executeQuery",
              "class": "Doctrine\\DBAL\\Connection",
              "type": "->"
            },
            {
              "file": "nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
              "line": 1843,
              "function": "executeQuery",
              "class": "OC\\DB\\Connection",
              "type": "->"
            },
            {
              "file": "nextcloud/lib/private/DB/Migrator.php",
              "line": 162,
              "function": "query",
              "class": "Doctrine\\DBAL\\Connection",
              "type": "->"
            },
            {
              "file": "nextcloud/lib/private/DB/Migrator.php",
              "line": 68,
              "function": "applySchema",
              "class": "OC\\DB\\Migrator",
              "type": "->"
            },
            {
              "file": "nextcloud/lib/private/DB/Connection.php",
              "line": 589,
              "function": "migrate",
              "class": "OC\\DB\\Migrator",
              "type": "->"
            },
            {
              "file": "nextcloud/lib/private/DB/MigrationService.php",
              "line": 532,
              "function": "migrateToSchema",
              "class": "OC\\DB\\Connection",
              "type": "->"
            },
            {
              "file": "nextcloud/lib/private/DB/MigrationService.php",
              "line": 417,
              "function": "executeStep",
              "class": "OC\\DB\\MigrationService",
              "type": "->"
            },
            {
              "file": "nextcloud/lib/private/legacy/OC_App.php",
              "line": 844,
              "function": "migrate",
              "class": "OC\\DB\\MigrationService",
              "type": "->"
            },
            {
              "file": "nextcloud/lib/private/Updater.php",
              "line": 359,
              "function": "updateApp",
              "class": "OC_App",
              "type": "::",
              "args": [
                "*** sensitive parameters replaced ***"
              ]
            },
            {
              "file": "nextcloud/lib/private/Updater.php",
              "line": 271,
              "function": "doAppUpgrade",
              "class": "OC\\Updater",
              "type": "->"
            },
            {
              "file": "nextcloud/lib/private/Updater.php",
              "line": 139,
              "function": "doUpgrade",
              "class": "OC\\Updater",
              "type": "->"
            },
            {
              "file": "nextcloud/core/Command/Upgrade.php",
              "line": 225,
              "function": "upgrade",
              "class": "OC\\Updater",
              "type": "->"
            },
            {
              "file": "nextcloud/3rdparty/symfony/console/Command/Command.php",
              "line": 298,
              "function": "execute",
              "class": "OC\\Core\\Command\\Upgrade",
              "type": "->"
            },
            {
              "file": "nextcloud/3rdparty/symfony/console/Application.php",
              "line": 1040,
              "function": "run",
              "class": "Symfony\\Component\\Console\\Command\\Command",
              "type": "->"
            },
            {
              "file": "nextcloud/3rdparty/symfony/console/Application.php",
              "line": 301,
              "function": "doRunCommand",
              "class": "Symfony\\Component\\Console\\Application",
              "type": "->"
            },
            {
              "file": "nextcloud/3rdparty/symfony/console/Application.php",
              "line": 171,
              "function": "doRun",
              "class": "Symfony\\Component\\Console\\Application",
              "type": "->"
            },
            {
              "file": "nextcloud/lib/private/Console/Application.php",
              "line": 211,
              "function": "run",
              "class": "Symfony\\Component\\Console\\Application",
              "type": "->"
            },
            {
              "file": "nextcloud/console.php",
              "line": 100,
              "function": "run",
              "class": "OC\\Console\\Application",
              "type": "->"
            },
            {
              "file": "nextcloud/occ",
              "line": 11,
              "args": [
                "nextcloud/console.php"
              ],
              "function": "require_once"
            }
          ],
          "File": "nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php",
          "Line": 72
        }
      }
    },
    "message": "Database error when running migration 020800Date20230911000000 for app collectives\nAn exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERREUR:  la colonne « settings » contient des valeurs NULL",
    "exception": {},
    "CustomMessage": "Database error when running migration 020800Date20230911000000 for app collectives\nAn exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERREUR:  la colonne « settings » contient des valeurs NULL"
  }
}
{
  "reqId": "xjd4W7SGEpuHj3CSb30v",
  "level": 3,
  "time": "2023-10-02T15:55:32+02:00",
  "remoteAddr": "",
  "user": "--",
  "app": "updater",
  "method": "",
  "url": "--",
  "message": "\\OC\\Updater::failure: Exception: Database error when running migration 020800Date20230911000000 for app collectives\nAn exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERREUR:  la colonne « settings » contient des valeurs NULL",
  "userAgent": "--",
  "version": "27.1.1.0",
  "data": {
    "app": "updater"
  }
}

</pre>
</details>

**Comment by max-nextcloud** [comment]
> I'd make sure to have some elements in the `collectives_u_settings` table _before_ the migration is executed, otherwise the issue won't be triggered. Do you have some fixtures for your test?

That's probably the reason why the upgrade is still passing on the test job. We do create collectives before the migration test but we don't seed any content or user settings (yet).

**Pull request merged**
